// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:task_app/appConfig.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: AppConfig.WEB_APIKEY,
    appId: AppConfig.APP_ID,
    messagingSenderId: AppConfig.MESSAGE_SENDING_ID,
    projectId: AppConfig.PROJECT_ID,
    authDomain: 'todo-5059a.firebaseapp.com',
    storageBucket: AppConfig.STORAGE_BUCKET,
    measurementId: 'G-H46F4LV41X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppConfig.ANDROID_APIKEY,
    appId: AppConfig.APP_ID,
    messagingSenderId: AppConfig.MESSAGE_SENDING_ID,
    projectId: AppConfig.PROJECT_ID,
    storageBucket: AppConfig.STORAGE_BUCKET,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: AppConfig.WINDOWS_APIKEY,
    appId: AppConfig.APP_ID,
    messagingSenderId: AppConfig.MESSAGE_SENDING_ID,
    projectId: AppConfig.PROJECT_ID,
    authDomain: 'todo-5059a.firebaseapp.com',
    storageBucket: AppConfig.STORAGE_BUCKET,
    measurementId: 'G-KRFBS5CM1C',
  );
}
